#!/bin/bash
# coding: utf8
echo $(date +%F_%T)

## 镜像加速-daocloud
curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://43049fd0.m.daocloud.io
## stop firewalld
systemctl stop firewalld
systemctl disabled firewalld
:<<!
被注释的多行内容 
yum install docker
yum install docker-ce
yum install docker
cat /etc/docker/daemon.json
{
      "registry-mirrors": ["https://registry.docker-cn.com"]
}
service docker restart
docker search gitlab
docker pull docker.io/gitlab/gitlab-ce
!

### centos7--jenkins
docker run -d \
  -p 8888:8080 \
  -p 50000:50000 \
  -v /opt/data/jenkins_home/:/var/jenkins_home \
  --name jenkins8888  \
  jenkins/jenkins:lts

### centos7--gitlab
docker run -d \
  --hostname gitlab.example.com \
  -p 443:443 \
  -p 8080:80 \
  -p 2222:22 \
  --name gitlab \
  --restart always \
  -v /opt/data/gitlab/config:/etc/gitlab \
  -v /opt/data/gitlab/logs:/var/log/gitlab \
  -v /opt/data/gitlab/data:/var/opt/gitlab \
  -v /etc/localtime:/etc/localtime \
  gitlab/gitlab-ce:latest

### vim /opt/data/gitlab/config/gitlab.rb
[root@gitlab config]# cd /opt/data/gitlab/config
[root@gitlab config]# grep -v "^#" gitlab.rb |grep -v ^$
external_url 'https://gitlab.example.com'

### gitlab-zh
docker run -d \
  --hostname gitlab.channel.com \
  -p 4443:443 \
  -p 8888:80 \
  -p 22222:22 \
  --name gitlab_zh \
  --restart always \
  -v /opt/data/gitlab_zh/config:/etc/gitlab \
  -v /opt/data/gitlab_zh/logs:/var/log/gitlab \
  -v /opt/data/gitlab_zh/data:/var/opt/gitlab \
  -v /etc/localtime:/etc/localtime \
  twang2218/gitlab-ce-zh:latest
  
## 使用默认的gitlab.rb
## 直接访问即可：http://gitlab.channel.com:8888


